### PR TITLE
Use dedicated servers for testing

### LINKED ISSUE #114: Use a dedicated Redis server for testing
#113

### LINKED ISSUE #119: Fix beforeEach test
The way `beforeEach` functions are executed now is not sufficient. 
https://github.com/denolib/deno-redis/blob/96b27457004cbcdb1032066bd70d9527d352873e/tests/test_util.ts#L37-L40
The promise resulted from `f()` is not waited in 
https://github.com/denolib/deno-redis/blob/96b27457004cbcdb1032066bd70d9527d352873e/tests/test_util.ts#L44
so putting client call in `beforeEach` results in error because client has been closed by `afterAll`.

Reproduce
```ts
const suite = new TestSuite("command");

const server = await startRedis({ port: 6500 });
const opts = { hostname: "127.0.0.1", port: 6500 };
const client = await newClient(opts);

suite.beforeEach(async () => {
  await client.flushdb();
});

suite.afterAll(() => {
  stopRedis(server);
  client.close();
});

suite.test("set", async () => {
  assertEquals(await client.set("key", "foo"), "OK");
});

suite.test("keys", async () => {
  await client.set("key1", "foo");
  await client.set("key2", "bar");
  const v = await client.keys("key*");
  console.log(await client.get("key"));
  assertEquals(v.sort(), ["key1", "key2"]);
});

await suite.runTests();

// 
deno test -A tests/command_test.ts
foo
running 2 tests
test [command] set ... error: Uncaught BadResource: Bad resource ID 
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:46:18)
    at async Object.writeAll ($deno$/buffer.ts:204:17)
    at async BufWriter.flush (bufio.ts:467:7)
    at async sendCommand (io.ts:63:3)
```

### PR DESCRIPTION
**Pull request by tumile**
Closes #114, closes #119 

Changes
- [x] Migrate from `makeTest` to `TestSuite` for all tests inside `tests`. Each test file uses one dedicated server. Tried to put all command tests in a single file, but some tests modify redis in a way that conflicts others.
- [x] Simplify CI and makefile a bit since we don't need to start redis from CI anymore
- [x] Move `pipeline_test` and `pubsub_test` into main tests folder
- [x] As said in #119, I updated how tests are executed to fix `beforeEachs` not resolved

### CODE REVIEW

**Comment by tumile** [comment]
pinging @uki00a for review

**Comment by uki00a** [comment]
@tumile Thanks for working this!
I've opened a PR for your branch.
Please check it out!
https://github.com/tumile/deno-redis/pull/1

**Comment by tumile** [comment]
Ready for review again! :D

**Comment by uki00a** [comment]
LGTM, thanks @tumile!

**Pull request merged**
